import '../styles/app.scss';

export const metadata = {
  title: 'Bytebank',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="shortcut icon" href="/favicons/bytebank_48px.png" />
        <link rel="shortcut icon" href="/favicons/bytebank_64px.png" />
      </head>
      <body>{children}</body>
    </html>
  )
}
